// ============================================================
// LANGUAGE.JS — 8 ЯЗЫКОВ ИНТЕРФЕЙСА
// ============================================================

const translations = {
    en: {
        badge: '🏦 PREMIUM TOKEN',
        title: 'Monaco Capital Frank',
        subtitle: 'Digital asset of a new generation',
        description: 'Premium token on Solana inspired by the financial heritage of Monaco. 0.25% commission is directed to development, marketing and listings.',
        supply: '10B',
        supply_label: 'Total Supply',
        fee_label: 'Transfer fee',
        chain: 'Solana',
        chain_label: 'Blockchain',
        buy_btn: '🚀 Buy MCF',
        liquidity_btn: '💧 Add Liquidity',
        explorer_btn: '🔍 Check Token',
        mint_label: 'Mint Address:',
        total_supply: 'Total Supply',
        holders: 'Holders',
        liquidity: 'Liquidity',
        volume: '24h Volume',
        apy: 'Staking APY',
        community: 'Community',
        timer_title: 'Until listing on Meteora:',
        days: 'Days',
        hours: 'Hours',
        minutes: 'Minutes',
        seconds: 'Seconds',
        timer_sub: 'Follow updates in our Telegram',
        chart_title: '📊 MCF Price Chart',
        ecosystem_title: '🏛️ MCF Ecosystem',
        ecosystem_sub: 'Inspired by the financial heritage of Monaco and Edmond de Rothschild bank',
        private_banking: 'Private Banking',
        private_banking_desc: 'Personal banking for holders of 100K+ MCF',
        wealth_management: 'Wealth Management',
        wealth_management_desc: 'Capital management with AI advisor',
        esg: 'ESG & Sustainability',
        esg_desc: 'Sustainable development and social responsibility',
        real_estate: 'Real Estate',
        real_estate_desc: 'Investments in elite real estate of Monaco',
        yachts: 'Yacht Services',
        yachts_desc: 'Yachts, charters and maritime services',
        casino: 'Casino & Entertainment',
        casino_desc: 'Monte Carlo — exclusive entertainment',
        partners_title: '🤝 Our partners',
        partners_sub: 'We cooperate with leading companies of Monaco and the world',
        roadmap_title: '🗺️ Roadmap',
        roadmap_sub: 'Stages of MCF project development',
        phase1_title: 'Creation of MCF token',
        phase1_desc: 'Mint on Solana, logo development, metadata upload. Full infrastructure preparation.',
        phase2_title: 'Listing on Meteora',
        phase2_desc: 'Adding liquidity, start of trading, integration with Jupiter and other aggregators.',
        phase3_title: 'CoinGecko & CoinMarketCap',
        phase3_desc: 'Applications for listing, global recognition, first major partnerships.',
        phase4_title: 'Ecosystem and partnerships',
        phase4_desc: 'Integrations with real business in Monaco, launch of staking, community expansion.',
        phase5_title: 'International recognition',
        phase5_desc: 'Listing on top exchanges, strategic partnerships, global scaling.',
        staking_title: '💰 MCF Staking',
        staking_sub: 'Earn up to 15% APY by locking your tokens',
        staking_flex: 'Flexible staking',
        staking_optimal: 'Optimal choice',
        staking_long: 'Maximum income',
        stake_btn: 'Start',
        faq_title: '❓ Frequently Asked Questions',
        faq_sub: 'Everything you need to know about MCF',
        faq1_q: 'What is MCF?',
        faq1_a: 'MCF (Monaco Capital Frank) is a premium token on the Solana blockchain, inspired by the financial heritage of Monaco. With a total supply of 10B and a 0.25% commission for development.',
        faq2_q: 'How to buy MCF?',
        faq2_a: 'You can buy MCF through Jupiter, Meteora or Raydium. Connect Phantom wallet, select MCF/USDC or MCF/SOL pair and make an exchange.',
        faq3_q: 'What is the transfer fee for MCF?',
        faq3_a: 'Transfer fee is 0.25%. These funds are directed to project development, marketing and listings, ensuring sustainable growth of the ecosystem.',
        faq4_q: 'Where to store MCF?',
        faq4_a: 'You can store MCF in any Solana wallet: Phantom, Solflare, Backpack. Just add the token by Mint Address: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'What is the MCF ecosystem?',
        faq5_a: 'MCF is inspired by the ecosystem of Edmond de Rothschild Monaco — private banking, capital management, real estate investments, yachts and luxury services.',
        faq6_q: 'When is the listing on exchanges?',
        faq6_a: 'MCF is already trading on Meteora. The next plans include applications for CoinGecko and CoinMarketCap. Follow updates in our social networks.',
        subscribe_title: '📬 Stay informed',
        subscribe_sub: 'Subscribe to our news and get updates first',
        subscribe_btn: 'Subscribe',
        footer_desc: 'Monaco Capital Frank — premium token on Solana, inspired by the financial heritage of Monaco.',
        footer_links: 'Links',
        footer_ecosystem: 'Ecosystem',
        footer_disclaimer: 'MCF is an independent project. Not an investment recommendation.',
        nav_home: 'Home',
        nav_stats: 'Stats',
        nav_ecosystem: 'Ecosystem',
        nav_roadmap: 'Roadmap',
        nav_staking: 'Staking',
        nav_partners: 'Partners',
        counters_title: '📊 Key Metrics',
        counters_sub: 'Real statistics of MCF token',
        news_label: 'News:'
    },
    ru: {
        badge: '🏦 PREMIUM TOKEN',
        title: 'Monaco Capital Frank',
        subtitle: 'Цифровой актив нового поколения',
        description: 'Премиальный токен на Solana, вдохновлённый финансовым наследием Монако. Комиссия 0.25% направляется на развитие, маркетинг и листинги.',
        supply: '10B',
        supply_label: 'Общая эмиссия',
        fee_label: 'Трансфер-фи',
        chain: 'Solana',
        chain_label: 'Блокчейн',
        buy_btn: '🚀 Купить MCF',
        liquidity_btn: '💧 Добавить ликвидность',
        explorer_btn: '🔍 Проверить токен',
        mint_label: 'Mint Address:',
        total_supply: 'Общая эмиссия',
        holders: 'Держателей',
        liquidity: 'Ликвидность',
        volume: 'Объём за 24ч',
        apy: 'APY стейкинга',
        community: 'Сообщество',
        timer_title: 'До листинга на Meteora:',
        days: 'Дней',
        hours: 'Часов',
        minutes: 'Минут',
        seconds: 'Секунд',
        timer_sub: 'Следите за обновлениями в нашем Telegram',
        chart_title: '📊 График цены MCF',
        ecosystem_title: '🏛️ Экосистема MCF',
        ecosystem_sub: 'Вдохновлённая финансовым наследием Монако и банком Edmond de Rothschild',
        private_banking: 'Private Banking',
        private_banking_desc: 'Персональный банкинг для держателей 100K+ MCF',
        wealth_management: 'Wealth Management',
        wealth_management_desc: 'Управление капиталом с AI-советником',
        esg: 'ESG & Sustainability',
        esg_desc: 'Устойчивое развитие и социальная ответственность',
        real_estate: 'Real Estate',
        real_estate_desc: 'Инвестиции в элитную недвижимость Монако',
        yachts: 'Yacht Services',
        yachts_desc: 'Яхты, чартеры и морские услуги',
        casino: 'Casino & Entertainment',
        casino_desc: 'Монте-Карло — эксклюзивные развлечения',
        partners_title: '🤝 Наши партнёры',
        partners_sub: 'Мы сотрудничаем с ведущими компаниями Монако и мира',
        roadmap_title: '🗺️ Дорожная карта',
        roadmap_sub: 'Этапы развития проекта MCF',
        phase1_title: 'Создание токена MCF',
        phase1_desc: 'Mint на Solana, разработка логотипа, загрузка метаданных. Полная подготовка инфраструктуры.',
        phase2_title: 'Листинг на Meteora',
        phase2_desc: 'Добавление ликвидности, начало торгов, интеграция с Jupiter и другими агрегаторами.',
        phase3_title: 'CoinGecko & CoinMarketCap',
        phase3_desc: 'Подача заявок на листинг, глобальное признание, первые крупные партнёрства.',
        phase4_title: 'Экосистема и партнёрства',
        phase4_desc: 'Интеграции с реальным бизнесом в Монако, запуск стейкинга, расширение сообщества.',
        phase5_title: 'Международное признание',
        phase5_desc: 'Листинг на топ-биржи, стратегические партнёрства, глобальное масштабирование.',
        staking_title: '💰 Стейкинг MCF',
        staking_sub: 'Зарабатывайте до 15% APY, блокируя свои токены',
        staking_flex: 'Гибкий стейкинг',
        staking_optimal: 'Оптимальный выбор',
        staking_long: 'Максимальный доход',
        stake_btn: 'Начать',
        faq_title: '❓ Часто задаваемые вопросы',
        faq_sub: 'Всё, что нужно знать о MCF',
        faq1_q: 'Что такое MCF?',
        faq1_a: 'MCF (Monaco Capital Frank) — это премиальный токен на блокчейне Solana, вдохновлённый финансовым наследием Монако. С общей эмиссией 10B и комиссией 0.25% на развитие.',
        faq2_q: 'Как купить MCF?',
        faq2_a: 'Вы можете купить MCF через Jupiter, Meteora или Raydium. Подключите Phantom кошелёк, выберите пару MCF/USDC или MCF/SOL и совершите обмен.',
        faq3_q: 'Какой трансфер-фи у MCF?',
        faq3_a: 'Трансфер-фи составляет 0.25%. Эти средства направляются на развитие проекта, маркетинг и листинги, что обеспечивает устойчивый рост экосистемы.',
        faq4_q: 'Где хранить MCF?',
        faq4_a: 'Вы можете хранить MCF в любом Solana-кошельке: Phantom, Solflare, Backpack. Просто добавьте токен по Mint Address: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'Какая экосистема у MCF?',
        faq5_a: 'MCF вдохновлён экосистемой Edmond de Rothschild Monaco — частным банкингом, управлением капиталом, инвестициями в недвижимость, яхтами и люксовыми услугами.',
        faq6_q: 'Когда листинг на биржах?',
        faq6_a: 'MCF уже торгуется на Meteora. В ближайших планах — подача на CoinGecko и CoinMarketCap. Следите за обновлениями в наших соцсетях.',
        subscribe_title: '📬 Будьте в курсе',
        subscribe_sub: 'Подпишитесь на наши новости и получайте обновления первыми',
        subscribe_btn: 'Подписаться',
        footer_desc: 'Monaco Capital Frank — премиальный токен на Solana, вдохновлённый финансовым наследием Монако.',
        footer_links: 'Ссылки',
        footer_ecosystem: 'Экосистема',
        footer_disclaimer: 'MCF — независимый проект. Не является инвестиционной рекомендацией.',
        nav_home: 'Главная',
        nav_stats: 'Статистика',
        nav_ecosystem: 'Экосистема',
        nav_roadmap: 'Дорожная карта',
        nav_staking: 'Стейкинг',
        nav_partners: 'Партнёры',
        counters_title: '📊 Ключевые показатели',
        counters_sub: 'Реальная статистика токена MCF',
        news_label: 'Новости:'
    },
    fr: {
        badge: '🏦 TOKEN PREMIUM',
        title: 'Monaco Capital Frank',
        subtitle: 'Actif numérique de nouvelle génération',
        description: 'Token premium sur Solana inspiré par le patrimoine financier de Monaco. 0.25% de commission est alloué au développement, au marketing et aux cotations.',
        supply: '10B',
        supply_label: 'Offre totale',
        fee_label: 'Frais de transfert',
        chain: 'Solana',
        chain_label: 'Blockchain',
        buy_btn: '🚀 Acheter MCF',
        liquidity_btn: '💧 Ajouter de la liquidité',
        explorer_btn: '🔍 Vérifier le token',
        mint_label: 'Mint Address:',
        total_supply: 'Offre totale',
        holders: 'Détenteurs',
        liquidity: 'Liquidité',
        volume: 'Volume 24h',
        apy: 'APY Staking',
        community: 'Communauté',
        timer_title: "Jusqu'à la cotation sur Meteora:",
        days: 'Jours',
        hours: 'Heures',
        minutes: 'Minutes',
        seconds: 'Secondes',
        timer_sub: 'Suivez les mises à jour dans notre Telegram',
        chart_title: '📊 Graphique des prix MCF',
        ecosystem_title: '🏛️ Écosystème MCF',
        ecosystem_sub: "Inspiré par l'héritage financier de Monaco et de la banque Edmond de Rothschild",
        private_banking: 'Private Banking',
        private_banking_desc: 'Banque personnelle pour les détenteurs de 100K+ MCF',
        wealth_management: 'Wealth Management',
        wealth_management_desc: 'Gestion de patrimoine avec conseiller IA',
        esg: 'ESG & Durabilité',
        esg_desc: 'Développement durable et responsabilité sociale',
        real_estate: 'Immobilier',
        real_estate_desc: "Investissements dans l'immobilier d'élite de Monaco",
        yachts: 'Services Yacht',
        yachts_desc: 'Yachts, charters et services maritimes',
        casino: 'Casino & Divertissement',
        casino_desc: 'Monte Carlo — divertissements exclusifs',
        partners_title: '🤝 Nos partenaires',
        partners_sub: 'Nous coopérons avec les principales entreprises de Monaco et du monde',
        roadmap_title: '🗺️ Feuille de route',
        roadmap_sub: "Étapes du développement du projet MCF",
        phase1_title: 'Création du token MCF',
        phase1_desc: 'Mint sur Solana, développement du logo, téléchargement des métadonnées. Préparation complète de l\'infrastructure.',
        phase2_title: 'Cotation sur Meteora',
        phase2_desc: 'Ajout de liquidité, début des échanges, intégration avec Jupiter et autres agrégateurs.',
        phase3_title: 'CoinGecko & CoinMarketCap',
        phase3_desc: 'Demandes de cotation, reconnaissance mondiale, premiers grands partenariats.',
        phase4_title: 'Écosystème et partenariats',
        phase4_desc: 'Intégrations avec les entreprises réelles à Monaco, lancement du staking, expansion de la communauté.',
        phase5_title: 'Reconnaissance internationale',
        phase5_desc: 'Cotation sur les principales bourses, partenariats stratégiques, mise à l\'échelle mondiale.',
        staking_title: '💰 Staking MCF',
        staking_sub: 'Gagnez jusqu\'à 15% APY en verrouillant vos tokens',
        staking_flex: 'Staking flexible',
        staking_optimal: 'Choix optimal',
        staking_long: 'Revenu maximum',
        stake_btn: 'Commencer',
        faq_title: '❓ Questions fréquentes',
        faq_sub: 'Tout ce que vous devez savoir sur MCF',
        faq1_q: 'Qu\'est-ce que MCF?',
        faq1_a: 'MCF (Monaco Capital Frank) est un token premium sur la blockchain Solana, inspiré par le patrimoine financier de Monaco. Avec une offre totale de 10B et une commission de 0.25% pour le développement.',
        faq2_q: 'Comment acheter MCF?',
        faq2_a: 'Vous pouvez acheter MCF via Jupiter, Meteora ou Raydium. Connectez votre portefeuille Phantom, sélectionnez la paire MCF/USDC ou MCF/SOL et effectuez l\'échange.',
        faq3_q: 'Quels sont les frais de transfert de MCF?',
        faq3_a: 'Les frais de transfert sont de 0.25%. Ces fonds sont alloués au développement du projet, au marketing et aux cotations, assurant une croissance durable de l\'écosystème.',
        faq4_q: 'Où stocker MCF?',
        faq4_a: 'Vous pouvez stocker MCF dans n\'importe quel portefeuille Solana: Phantom, Solflare, Backpack. Ajoutez simplement le token par Mint Address: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'Quel est l\'écosystème de MCF?',
        faq5_a: 'MCF est inspiré par l\'écosystème d\'Edmond de Rothschild Monaco — banque privée, gestion de capital, investissements immobiliers, yachts et services de luxe.',
        faq6_q: 'Quand la cotation sur les bourses?',
        faq6_a: 'MCF est déjà coté sur Meteora. Les prochains plans incluent les demandes pour CoinGecko et CoinMarketCap. Suivez les mises à jour sur nos réseaux sociaux.',
        subscribe_title: '📬 Restez informé',
        subscribe_sub: 'Abonnez-vous à nos actualités et recevez les mises à jour en premier',
        subscribe_btn: 'S\'abonner',
        footer_desc: 'Monaco Capital Frank — token premium sur Solana, inspiré par le patrimoine financier de Monaco.',
        footer_links: 'Liens',
        footer_ecosystem: 'Écosystème',
        footer_disclaimer: 'MCF est un projet indépendant. Ce n\'est pas une recommandation d\'investissement.',
        nav_home: 'Accueil',
        nav_stats: 'Stats',
        nav_ecosystem: 'Écosystème',
        nav_roadmap: 'Feuille de route',
        nav_staking: 'Staking',
        nav_partners: 'Partenaires',
        counters_title: '📊 Indicateurs clés',
        counters_sub: 'Statistiques réelles du token MCF',
        news_label: 'Actualités:'
    },
    de: {
        badge: '🏦 PREMIUM TOKEN',
        title: 'Monaco Capital Frank',
        subtitle: 'Digitaler Vermögenswert der neuen Generation',
        description: 'Premium-Token auf Solana, inspiriert vom finanziellen Erbe Monacos. 0.25% der Provision fließen in Entwicklung, Marketing und Listings.',
        supply: '10B',
        supply_label: 'Gesamtangebot',
        fee_label: 'Transfergebühr',
        chain: 'Solana',
        chain_label: 'Blockchain',
        buy_btn: '🚀 MCF kaufen',
        liquidity_btn: '💧 Liquidität hinzufügen',
        explorer_btn: '🔍 Token prüfen',
        mint_label: 'Mint Address:',
        total_supply: 'Gesamtangebot',
        holders: 'Inhaber',
        liquidity: 'Liquidität',
        volume: '24h Volumen',
        apy: 'Staking APY',
        community: 'Community',
        timer_title: 'Bis zum Listing auf Meteora:',
        days: 'Tage',
        hours: 'Stunden',
        minutes: 'Minuten',
        seconds: 'Sekunden',
        timer_sub: 'Verfolgen Sie Updates in unserem Telegram',
        chart_title: '📊 MCF Preis-Chart',
        ecosystem_title: '🏛️ MCF Ökosystem',
        ecosystem_sub: 'Inspiriert vom finanziellen Erbe Monacos und der Edmond de Rothschild Bank',
        private_banking: 'Private Banking',
        private_banking_desc: 'Persönliches Banking für Inhaber von 100K+ MCF',
        wealth_management: 'Vermögensverwaltung',
        wealth_management_desc: 'Kapitalverwaltung mit AI-Berater',
        esg: 'ESG & Nachhaltigkeit',
        esg_desc: 'Nachhaltige Entwicklung und soziale Verantwortung',
        real_estate: 'Immobilien',
        real_estate_desc: 'Investitionen in Elite-Immobilien in Monaco',
        yachts: 'Yacht-Services',
        yachts_desc: 'Yachten, Charters und maritime Dienstleistungen',
        casino: 'Casino & Unterhaltung',
        casino_desc: 'Monte Carlo — exklusive Unterhaltung',
        partners_title: '🤝 Unsere Partner',
        partners_sub: 'Wir kooperieren mit führenden Unternehmen in Monaco und weltweit',
        roadmap_title: '🗺️ Roadmap',
        roadmap_sub: 'Entwicklungsstufen des MCF-Projekts',
        phase1_title: 'Erstellung des MCF-Tokens',
        phase1_desc: 'Mint auf Solana, Logo-Entwicklung, Metadaten-Upload. Vollständige Infrastrukturvorbereitung.',
        phase2_title: 'Listing auf Meteora',
        phase2_desc: 'Hinzufügen von Liquidität, Start des Handels, Integration mit Jupiter und anderen Aggregatoren.',
        phase3_title: 'CoinGecko & CoinMarketCap',
        phase3_desc: 'Listing-Anträge, globale Anerkennung, erste große Partnerschaften.',
        phase4_title: 'Ökosystem und Partnerschaften',
        phase4_desc: 'Integrationen mit realen Unternehmen in Monaco, Start von Staking, Community-Erweiterung.',
        phase5_title: 'Internationale Anerkennung',
        phase5_desc: 'Listing auf Top-Börsen, strategische Partnerschaften, globale Skalierung.',
        staking_title: '💰 MCF Staking',
        staking_sub: 'Verdienen Sie bis zu 15% APY durch Sperrung Ihrer Tokens',
        staking_flex: 'Flexibles Staking',
        staking_optimal: 'Optimale Wahl',
        staking_long: 'Maximales Einkommen',
        stake_btn: 'Starten',
        faq_title: '❓ Häufige Fragen',
        faq_sub: 'Alles, was Sie über MCF wissen müssen',
        faq1_q: 'Was ist MCF?',
        faq1_a: 'MCF (Monaco Capital Frank) ist ein Premium-Token auf der Solana-Blockchain, inspiriert vom finanziellen Erbe Monacos. Mit einem Gesamtangebot von 10B und einer Entwicklungsgebühr von 0.25%.',
        faq2_q: 'Wie kaufe ich MCF?',
        faq2_a: 'Sie können MCF über Jupiter, Meteora oder Raydium kaufen. Verbinden Sie Ihre Phantom-Wallet, wählen Sie das Paar MCF/USDC oder MCF/SOL und tauschen Sie.',
        faq3_q: 'Wie hoch ist die Transfergebühr für MCF?',
        faq3_a: 'Die Transfergebühr beträgt 0.25%. Diese Mittel fließen in die Projektentwicklung, Marketing und Listings, was ein nachhaltiges Wachstum des Ökosystems gewährleistet.',
        faq4_q: 'Wo kann ich MCF aufbewahren?',
        faq4_a: 'Sie können MCF in jeder Solana-Wallet aufbewahren: Phantom, Solflare, Backpack. Fügen Sie den Token einfach über die Mint Address hinzu: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'Was ist das MCF-Ökosystem?',
        faq5_a: 'MCF ist vom Ökosystem von Edmond de Rothschild Monaco inspiriert — Private Banking, Kapitalverwaltung, Immobilieninvestitionen, Yachten und Luxusdienstleistungen.',
        faq6_q: 'Wann kommt das Listing auf Börsen?',
        faq6_a: 'MCF wird bereits auf Meteora gehandelt. Die nächsten Pläne umfassen Anträge für CoinGecko und CoinMarketCap. Verfolgen Sie die Updates in unseren sozialen Netzwerken.',
        subscribe_title: '📬 Bleiben Sie informiert',
        subscribe_sub: 'Abonnieren Sie unsere Neuigkeiten und erhalten Sie Updates zuerst',
        subscribe_btn: 'Abonnieren',
        footer_desc: 'Monaco Capital Frank — Premium-Token auf Solana, inspiriert vom finanziellen Erbe Monacos.',
        footer_links: 'Links',
        footer_ecosystem: 'Ökosystem',
        footer_disclaimer: 'MCF ist ein unabhängiges Projekt. Keine Anlageempfehlung.',
        nav_home: 'Startseite',
        nav_stats: 'Stats',
        nav_ecosystem: 'Ökosystem',
        nav_roadmap: 'Roadmap',
        nav_staking: 'Staking',
        nav_partners: 'Partner',
        counters_title: '📊 Wichtige Kennzahlen',
        counters_sub: 'Reale Statistik des MCF-Tokens',
        news_label: 'Neuigkeiten:'
    },
    es: {
        badge: '🏦 TOKEN PREMIUM',
        title: 'Monaco Capital Frank',
        subtitle: 'Activo digital de nueva generación',
        description: 'Token premium en Solana inspirado en el patrimonio financiero de Mónaco. Comisión del 0.25% destinada al desarrollo, marketing y listados.',
        supply: '10B',
        supply_label: 'Oferta total',
        fee_label: 'Comisión de transferencia',
        chain: 'Solana',
        chain_label: 'Blockchain',
        buy_btn: '🚀 Comprar MCF',
        liquidity_btn: '💧 Añadir liquidez',
        explorer_btn: '🔍 Verificar token',
        mint_label: 'Mint Address:',
        total_supply: 'Oferta total',
        holders: 'Tenedores',
        liquidity: 'Liquidez',
        volume: 'Volumen 24h',
        apy: 'APY Staking',
        community: 'Comunidad',
        timer_title: 'Hasta el listado en Meteora:',
        days: 'Días',
        hours: 'Horas',
        minutes: 'Minutos',
        seconds: 'Segundos',
        timer_sub: 'Sigue las actualizaciones en nuestro Telegram',
        chart_title: '📊 Gráfico de precios MCF',
        ecosystem_title: '🏛️ Ecosistema MCF',
        ecosystem_sub: 'Inspirado en el patrimonio financiero de Mónaco y el banco Edmond de Rothschild',
        private_banking: 'Banca Privada',
        private_banking_desc: 'Banca personal para tenedores de 100K+ MCF',
        wealth_management: 'Gestión de Patrimonios',
        wealth_management_desc: 'Gestión de capital con asesor IA',
        esg: 'ESG & Sostenibilidad',
        esg_desc: 'Desarrollo sostenible y responsabilidad social',
        real_estate: 'Bienes Raíces',
        real_estate_desc: 'Inversiones en bienes raíces de élite en Mónaco',
        yachts: 'Servicios de Yates',
        yachts_desc: 'Yates, charters y servicios marítimos',
        casino: 'Casino & Entretenimiento',
        casino_desc: 'Monte Carlo — entretenimiento exclusivo',
        partners_title: '🤝 Nuestros socios',
        partners_sub: 'Cooperamos con las principales empresas de Mónaco y el mundo',
        roadmap_title: '🗺️ Hoja de ruta',
        roadmap_sub: 'Etapas de desarrollo del proyecto MCF',
        phase1_title: 'Creación del token MCF',
        phase1_desc: 'Mint en Solana, desarrollo del logo, carga de metadatos. Preparación completa de la infraestructura.',
        phase2_title: 'Listado en Meteora',
        phase2_desc: 'Adición de liquidez, inicio de operaciones, integración con Jupiter y otros agregadores.',
        phase3_title: 'CoinGecko & CoinMarketCap',
        phase3_desc: 'Solicitudes de listado, reconocimiento global, primeras grandes alianzas.',
        phase4_title: 'Ecosistema y alianzas',
        phase4_desc: 'Integraciones con negocios reales en Mónaco, lanzamiento de staking, expansión comunitaria.',
        phase5_title: 'Reconocimiento internacional',
        phase5_desc: 'Listado en los principales exchanges, alianzas estratégicas, escalado global.',
        staking_title: '💰 Staking MCF',
        staking_sub: 'Gane hasta un 15% APY bloqueando sus tokens',
        staking_flex: 'Staking flexible',
        staking_optimal: 'Elección óptima',
        staking_long: 'Ingreso máximo',
        stake_btn: 'Comenzar',
        faq_title: '❓ Preguntas frecuentes',
        faq_sub: 'Todo lo que necesita saber sobre MCF',
        faq1_q: '¿Qué es MCF?',
        faq1_a: 'MCF (Monaco Capital Frank) es un token premium en la blockchain Solana, inspirado en el patrimonio financiero de Mónaco. Con una oferta total de 10B y una comisión del 0.25% para el desarrollo.',
        faq2_q: '¿Cómo comprar MCF?',
        faq2_a: 'Puede comprar MCF a través de Jupiter, Meteora o Raydium. Conecte su billetera Phantom, seleccione el par MCF/USDC o MCF/SOL y realice el intercambio.',
        faq3_q: '¿Cuál es la comisión de transferencia de MCF?',
        faq3_a: 'La comisión de transferencia es del 0.25%. Estos fondos se destinan al desarrollo del proyecto, marketing y listados, asegurando un crecimiento sostenible del ecosistema.',
        faq4_q: '¿Dónde almacenar MCF?',
        faq4_a: 'Puede almacenar MCF en cualquier billetera Solana: Phantom, Solflare, Backpack. Simplemente agregue el token por Mint Address: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: '¿Cuál es el ecosistema de MCF?',
        faq5_a: 'MCF está inspirado en el ecosistema de Edmond de Rothschild Mónaco — banca privada, gestión de capital, inversiones inmobiliarias, yates y servicios de lujo.',
        faq6_q: '¿Cuándo es el listado en exchanges?',
        faq6_a: 'MCF ya se negocia en Meteora. Los próximos planes incluyen solicitudes para CoinGecko y CoinMarketCap. Siga las actualizaciones en nuestras redes sociales.',
        subscribe_title: '📬 Manténgase informado',
        subscribe_sub: 'Suscríbase a nuestras noticias y reciba actualizaciones primero',
        subscribe_btn: 'Suscribirse',
        footer_desc: 'Monaco Capital Frank — token premium en Solana, inspirado en el patrimonio financiero de Mónaco.',
        footer_links: 'Enlaces',
        footer_ecosystem: 'Ecosistema',
        footer_disclaimer: 'MCF es un proyecto independiente. No es una recomendación de inversión.',
        nav_home: 'Inicio',
        nav_stats: 'Estadísticas',
        nav_ecosystem: 'Ecosistema',
        nav_roadmap: 'Hoja de ruta',
        nav_staking: 'Staking',
        nav_partners: 'Socios',
        counters_title: '📊 Indicadores clave',
        counters_sub: 'Estadísticas reales del token MCF',
        news_label: 'Noticias:'
    },
    it: {
        badge: '🏦 TOKEN PREMIUM',
        title: 'Monaco Capital Frank',
        subtitle: 'Asset digitale di nuova generazione',
        description: 'Token premium su Solana ispirato al patrimonio finanziario di Monaco. Commissione dello 0.25% destinata allo sviluppo, marketing e quotazioni.',
        supply: '10B',
        supply_label: 'Offerta totale',
        fee_label: 'Commissione di trasferimento',
        chain: 'Solana',
        chain_label: 'Blockchain',
        buy_btn: '🚀 Compra MCF',
        liquidity_btn: '💧 Aggiungi liquidità',
        explorer_btn: '🔍 Verifica token',
        mint_label: 'Mint Address:',
        total_supply: 'Offerta totale',
        holders: 'Detentori',
        liquidity: 'Liquidità',
        volume: 'Volume 24h',
        apy: 'APY Staking',
        community: 'Comunità',
        timer_title: 'Fino alla quotazione su Meteora:',
        days: 'Giorni',
        hours: 'Ore',
        minutes: 'Minuti',
        seconds: 'Secondi',
        timer_sub: 'Segui gli aggiornamenti sul nostro Telegram',
        chart_title: '📊 Grafico prezzi MCF',
        ecosystem_title: '🏛️ Ecosistema MCF',
        ecosystem_sub: 'Ispirato al patrimonio finanziario di Monaco e alla banca Edmond de Rothschild',
        private_banking: 'Private Banking',
        private_banking_desc: 'Banca personale per detentori di 100K+ MCF',
        wealth_management: 'Wealth Management',
        wealth_management_desc: 'Gestione del capitale con consulente AI',
        esg: 'ESG & Sostenibilità',
        esg_desc: 'Sviluppo sostenibile e responsabilità sociale',
        real_estate: 'Immobiliare',
        real_estate_desc: 'Investimenti in immobili di lusso a Monaco',
        yachts: 'Servizi Yacht',
        yachts_desc: 'Yacht, charter e servizi marittimi',
        casino: 'Casinò & Intrattenimento',
        casino_desc: 'Monte Carlo — intrattenimento esclusivo',
        partners_title: '🤝 I nostri partner',
        partners_sub: 'Collaboriamo con le principali aziende di Monaco e del mondo',
        roadmap_title: '🗺️ Roadmap',
        roadmap_sub: 'Fasi di sviluppo del progetto MCF',
        phase1_title: 'Creazione del token MCF',
        phase1_desc: 'Mint su Solana, sviluppo del logo, caricamento dei metadati. Preparazione completa dell\'infrastruttura.',
        phase2_title: 'Quotazione su Meteora',
        phase2_desc: 'Aggiunta di liquidità, inizio delle negoziazioni, integrazione con Jupiter e altri aggregatori.',
        phase3_title: 'CoinGecko & CoinMarketCap',
        phase3_desc: 'Domande di quotazione, riconoscimento globale, prime grandi partnership.',
        phase4_title: 'Ecosistema e partnership',
        phase4_desc: 'Integrazioni con aziende reali a Monaco, lancio dello staking, espansione della comunità.',
        phase5_title: 'Riconoscimento internazionale',
        phase5_desc: 'Quotazione sui principali exchange, partnership strategiche, scalata globale.',
        staking_title: '💰 Staking MCF',
        staking_sub: 'Guadagna fino al 15% APY bloccando i tuoi token',
        staking_flex: 'Staking flessibile',
        staking_optimal: 'Scelta ottimale',
        staking_long: 'Reddito massimo',
        stake_btn: 'Inizia',
        faq_title: '❓ Domande frequenti',
        faq_sub: 'Tutto ciò che devi sapere su MCF',
        faq1_q: 'Cos\'è MCF?',
        faq1_a: 'MCF (Monaco Capital Frank) è un token premium sulla blockchain Solana, ispirato al patrimonio finanziario di Monaco. Con un\'offerta totale di 10B e una commissione dello 0.25% per lo sviluppo.',
        faq2_q: 'Come acquistare MCF?',
        faq2_a: 'Puoi acquistare MCF tramite Jupiter, Meteora o Raydium. Collega il tuo portafoglio Phantom, seleziona la coppia MCF/USDC o MCF/SOL ed effettua lo scambio.',
        faq3_q: 'Qual è la commissione di trasferimento di MCF?',
        faq3_a: 'La commissione di trasferimento è dello 0.25%. Questi fondi sono destinati allo sviluppo del progetto, al marketing e alle quotazioni, garantendo una crescita sostenibile dell\'ecosistema.',
        faq4_q: 'Dove conservare MCF?',
        faq4_a: 'Puoi conservare MCF in qualsiasi wallet Solana: Phantom, Solflare, Backpack. Aggiungi semplicemente il token tramite Mint Address: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'Qual è l\'ecosistema di MCF?',
        faq5_a: 'MCF è ispirato all\'ecosistema di Edmond de Rothschild Monaco — private banking, gestione del capitale, investimenti immobiliari, yacht e servizi di lusso.',
        faq6_q: 'Quando la quotazione sugli exchange?',
        faq6_a: 'MCF è già scambiato su Meteora. I prossimi piani includono richieste per CoinGecko e CoinMarketCap. Segui gli aggiornamenti sui nostri social.',
        subscribe_title: '📬 Rimani informato',
        subscribe_sub: 'Iscriviti alle nostre notizie e ricevi gli aggiornamenti per primo',
        subscribe_btn: 'Iscriviti',
        footer_desc: 'Monaco Capital Frank — token premium su Solana, ispirato al patrimonio finanziario di Monaco.',
        footer_links: 'Link',
        footer_ecosystem: 'Ecosistema',
        footer_disclaimer: 'MCF è un progetto indipendente. Non è una raccomandazione di investimento.',
        nav_home: 'Home',
        nav_stats: 'Statistiche',
        nav_ecosystem: 'Ecosistema',
        nav_roadmap: 'Roadmap',
        nav_staking: 'Staking',
        nav_partners: 'Partner',
        counters_title: '📊 Indicatori chiave',
        counters_sub: 'Statistiche reali del token MCF',
        news_label: 'Notizie:'
    },
    zh: {
        badge: '🏦 高级代币',
        title: 'Monaco Capital Frank',
        subtitle: '新一代数字资产',
        description: 'Solana上的高级代币，灵感来自摩纳哥的金融遗产。0.25%的费用用于开发、营销和上市。',
        supply: '10B',
        supply_label: '总供应量',
        fee_label: '转账费用',
        chain: 'Solana',
        chain_label: '区块链',
        buy_btn: '🚀 购买MCF',
        liquidity_btn: '💧 添加流动性',
        explorer_btn: '🔍 检查代币',
        mint_label: 'Mint地址:',
        total_supply: '总供应量',
        holders: '持有者',
        liquidity: '流动性',
        volume: '24小时交易量',
        apy: '质押APY',
        community: '社区',
        timer_title: '距Meteora上市:',
        days: '天',
        hours: '小时',
        minutes: '分钟',
        seconds: '秒',
        timer_sub: '在Telegram关注更新',
        chart_title: '📊 MCF价格图表',
        ecosystem_title: '🏛️ MCF生态系统',
        ecosystem_sub: '灵感来自摩纳哥的金融遗产和Edmond de Rothschild银行',
        private_banking: '私人银行',
        private_banking_desc: '为100K+ MCF持有者提供个人银行服务',
        wealth_management: '财富管理',
        wealth_management_desc: 'AI顾问资本管理',
        esg: 'ESG与可持续发展',
        esg_desc: '可持续发展和企业社会责任',
        real_estate: '房地产',
        real_estate_desc: '投资摩纳哥精英房地产',
        yachts: '游艇服务',
        yachts_desc: '游艇、租赁和海事服务',
        casino: '赌场与娱乐',
        casino_desc: '蒙特卡洛 — 独家娱乐',
        partners_title: '🤝 我们的合作伙伴',
        partners_sub: '我们与摩纳哥和世界领先的公司合作',
        roadmap_title: '🗺️ 路线图',
        roadmap_sub: 'MCF项目发展阶段',
        phase1_title: '创建MCF代币',
        phase1_desc: '在Solana上Mint，开发标志，上传元数据。完全的基础设施准备。',
        phase2_title: '在Meteora上市',
        phase2_desc: '添加流动性，开始交易，与Jupiter和其他聚合器集成。',
        phase3_title: 'CoinGecko和CoinMarketCap',
        phase3_desc: '申请上市，全球认可，首次大型合作。',
        phase4_title: '生态系统和合作伙伴关系',
        phase4_desc: '与摩纳哥真实企业整合，启动质押，扩大社区。',
        phase5_title: '国际认可',
        phase5_desc: '在顶级交易所上市，战略合作，全球扩张。',
        staking_title: '💰 MCF质押',
        staking_sub: '锁定您的代币，赚取高达15%的年化收益率',
        staking_flex: '灵活质押',
        staking_optimal: '最佳选择',
        staking_long: '最高收益',
        stake_btn: '开始',
        faq_title: '❓ 常见问题',
        faq_sub: '关于MCF的一切',
        faq1_q: '什么是MCF？',
        faq1_a: 'MCF (Monaco Capital Frank) 是Solana区块链上的高级代币，灵感来自摩纳哥的金融遗产。总供应量10B，0.25%的开发费用。',
        faq2_q: '如何购买MCF？',
        faq2_a: '您可以通过Jupiter、Meteora或Raydium购买MCF。连接Phantom钱包，选择MCF/USDC或MCF/SOL交易对进行兑换。',
        faq3_q: 'MCF的转账费用是多少？',
        faq3_a: '转账费为0.25%。这些资金用于项目开发、营销和上市，确保生态系统的可持续增长。',
        faq4_q: '在哪里存储MCF？',
        faq4_a: '您可以在任何Solana钱包中存储MCF：Phantom、Solflare、Backpack。只需按Mint地址添加代币：33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'MCF的生态系统是什么？',
        faq5_a: 'MCF的灵感来自Edmond de Rothschild Monaco生态系统 — 私人银行、资本管理、房地产投资、游艇和奢侈品服务。',
        faq6_q: '何时在交易所上市？',
        faq6_a: 'MCF已经在Meteora上交易。接下来的计划包括申请CoinGecko和CoinMarketCap。请关注我们社交媒体的更新。',
        subscribe_title: '📬 保持关注',
        subscribe_sub: '订阅我们的新闻，第一时间获取更新',
        subscribe_btn: '订阅',
        footer_desc: 'Monaco Capital Frank — Solana上的高级代币，灵感来自摩纳哥的金融遗产。',
        footer_links: '链接',
        footer_ecosystem: '生态系统',
        footer_disclaimer: 'MCF是一个独立项目。不是投资建议。',
        nav_home: '首页',
        nav_stats: '数据',
        nav_ecosystem: '生态系统',
        nav_roadmap: '路线图',
        nav_staking: '质押',
        nav_partners: '合作伙伴',
        counters_title: '📊 关键指标',
        counters_sub: 'MCF代币的真实统计数据',
        news_label: '新闻:'
    },
    ar: {
        badge: '🏦 رمز ممتاز',
        title: 'Monaco Capital Frank',
        subtitle: 'أصل رقمي من الجيل الجديد',
        description: 'رمز ممتاز على سولانا مستوحى من التراث المالي لموناكو. 0.25% من العمولة تذهب للتطوير والتسويق والإدراج.',
        supply: '10B',
        supply_label: 'العرض الكلي',
        fee_label: 'رسوم التحويل',
        chain: 'Solana',
        chain_label: 'سلسلة الكتل',
        buy_btn: '🚀 شراء MCF',
        liquidity_btn: '💧 إضافة سيولة',
        explorer_btn: '🔍 التحقق من الرمز',
        mint_label: 'عنوان الصك:',
        total_supply: 'العرض الكلي',
        holders: 'المالكين',
        liquidity: 'السيولة',
        volume: 'حجم 24 ساعة',
        apy: 'العائد السنوي للتجميد',
        community: 'المجتمع',
        timer_title: 'حتى الإدراج في Meteora:',
        days: 'أيام',
        hours: 'ساعات',
        minutes: 'دقائق',
        seconds: 'ثواني',
        timer_sub: 'تابع التحديثات في تيليغرام',
        chart_title: '📊 رسم بياني لسعر MCF',
        ecosystem_title: '🏛️ النظام البيئي MCF',
        ecosystem_sub: 'مستوحى من التراث المالي لموناكو وبنك Edmond de Rothschild',
        private_banking: 'الخدمات المصرفية الخاصة',
        private_banking_desc: 'خدمات مصرفية شخصية لحاملي 100K+ MCF',
        wealth_management: 'إدارة الثروات',
        wealth_management_desc: 'إدارة رأس المال مع مستشار ذكاء اصطناعي',
        esg: 'ESG والاستدامة',
        esg_desc: 'التنمية المستدامة والمسؤولية الاجتماعية',
        real_estate: 'العقارات',
        real_estate_desc: 'استثمارات في العقارات الفاخرة في موناكو',
        yachts: 'خدمات اليخوت',
        yachts_desc: 'اليخوت والتأجير والخدمات البحرية',
        casino: 'الكازينو والترفيه',
        casino_desc: 'مونتي كارلو — ترفيه حصري',
        partners_title: '🤝 شركاؤنا',
        partners_sub: 'نتعاون مع الشركات الرائدة في موناكو والعالم',
        roadmap_title: '🗺️ خريطة الطريق',
        roadmap_sub: 'مراحل تطوير مشروع MCF',
        phase1_title: 'إنشاء رمز MCF',
        phase1_desc: 'الصك على سولانا، تطوير الشعار، تحميل البيانات الوصفية. الإعداد الكامل للبنية التحتية.',
        phase2_title: 'الإدراج في Meteora',
        phase2_desc: 'إضافة السيولة، بدء التداول، التكامل مع Jupiter والمجمعات الأخرى.',
        phase3_title: 'CoinGecko و CoinMarketCap',
        phase3_desc: 'طلبات الإدراج، الاعتراف العالمي، أولى الشراكات الكبرى.',
        phase4_title: 'النظام البيئي والشراكات',
        phase4_desc: 'التكامل مع الأعمال الحقيقية في موناكو، إطلاق التجميد، توسيع المجتمع.',
        phase5_title: 'الاعتراف الدولي',
        phase5_desc: 'الإدراج في البورصات الكبرى، الشراكات الاستراتيجية، التوسع العالمي.',
        staking_title: '💰 تجميد MCF',
        staking_sub: 'اربح حتى 15% سنوياً عن طريق قفل رموزك',
        staking_flex: 'تجميد مرن',
        staking_optimal: 'الخيار الأمثل',
        staking_long: 'الحد الأقصى للدخل',
        stake_btn: 'ابدأ',
        faq_title: '❓ أسئلة شائعة',
        faq_sub: 'كل ما تحتاج معرفته عن MCF',
        faq1_q: 'ما هو MCF؟',
        faq1_a: 'MCF (Monaco Capital Frank) هو رمز ممتاز على سلسلة كتل سولانا، مستوحى من التراث المالي لموناكو. مع عرض إجمالي 10B وعمولة 0.25% للتطوير.',
        faq2_q: 'كيف أشتري MCF؟',
        faq2_a: 'يمكنك شراء MCF عبر Jupiter أو Meteora أو Raydium. قم بتوصيل محفظة Phantom، واختر زوج MCF/USDC أو MCF/SOL وقم بالتبادل.',
        faq3_q: 'ما هي رسوم تحويل MCF؟',
        faq3_a: 'رسوم التحويل هي 0.25%. يتم توجيه هذه الأموال لتطوير المشروع والتسويق والإدراج، مما يضمن النمو المستدام للنظام البيئي.',
        faq4_q: 'أين يمكن تخزين MCF؟',
        faq4_a: 'يمكنك تخزين MCF في أي محفظة سولانا: Phantom، Solflare، Backpack. فقط أضف الرمز بواسطة عنوان الصك: 33r46gDzoXfYijXWS4JgWcUcPWbTGphBnJGnApW77fsX',
        faq5_q: 'ما هو النظام البيئي لـ MCF؟',
        faq5_a: 'MCF مستوحى من النظام البيئي لـ Edmond de Rothschild Monaco — الخدمات المصرفية الخاصة، إدارة رأس المال، الاستثمارات العقارية، اليخوت والخدمات الفاخرة.',
        faq6_q: 'متى الإدراج في البورصات؟',
        faq6_a: 'يتم تداول MCF بالفعل في Meteora. تشمل الخطط القادمة طلبات CoinGecko و CoinMarketCap. تابع التحديثات على وسائل التواصل الاجتماعي الخاصة بنا.',
        subscribe_title: '📬 ابق على اطلاع',
        subscribe_sub: 'اشترك في أخبارنا واحصل على التحديثات أولاً',
        subscribe_btn: 'اشتراك',
        footer_desc: 'Monaco Capital Frank — رمز ممتاز على سولانا، مستوحى من التراث المالي لموناكو.',
        footer_links: 'روابط',
        footer_ecosystem: 'النظام البيئي',
        footer_disclaimer: 'MCF هو مشروع مستقل. ليس توصية استثمارية.',
        nav_home: 'الرئيسية',
        nav_stats: 'الإحصائيات',
        nav_ecosystem: 'النظام البيئي',
        nav_roadmap: 'خريطة الطريق',
        nav_staking: 'التجميد',
        nav_partners: 'الشركاء',
        counters_title: '📊 المؤشرات الرئيسية',
        counters_sub: 'إحصائيات حقيقية لرمز MCF',
        news_label: 'أخبار:'
    }
};

// ============================================================
// ПЕРЕКЛЮЧЕНИЕ ЯЗЫКА
// ============================================================
document.addEventListener('DOMContentLoaded', function() {
    // Загрузка сохранённого языка
    const savedLang = localStorage.getItem('mcf_language') || 'ru';
    setLanguage(savedLang);
    
    // Обработчики кнопок
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', function() {
            const lang = this.getAttribute('data-lang');
            setLanguage(lang);
            localStorage.setItem('mcf_language', lang);
            
            // Активный класс
            document.querySelectorAll('.lang-btn').forEach(b => b.classList.remove('active'));
            this.classList.add('active');
        });
    });
});

function setLanguage(lang) {
    const data = translations[lang];
    if (!data) return;
    
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (data[key]) {
            if (el.tagName === 'INPUT') {
                el.placeholder = data[key];
            } else {
                el.textContent = data[key];
            }
        }
    });
      }
